#!/bin/sh

echo "read zsh_activation"
 
zsh_activation(){
  zshpath=`which zsh`
  if [ $? -ne 0 ]
  then
    echo "zsh not found quit"
    return
  fi
  
  echo "current shell: $SHELL"
  echo "zsh path: $zshpath"
  if [ $SHELL = $zshpath ]
  then
    echo "already in zsh quit"
    return
  fi
  
  echo "Let's activate zsh ..."
  SHELL=$zshpath
  export SHELL
  exec $zshpath --login
}

zsh_activation
